project:
  type: website

website:
  title: "Docs"
  google-analytics: "UA-188412659-2"
  navbar:
    logo: logo.png
    logo-href: https://hal9.com
    title: false
    background: primary
#    left:
#      - text: "Python"
#        href: /python
#      - text: "R"
#        href: /r/reference
#      - text: "JavaScript"
#        href: /javascript/h9.html
  sidebar:
      style: "docked"
      search: true
      contents:
        - index.qmd
#        - section: "Overview"
#          contents:
#            - index.qmd
        - section: "Using"
          contents:
            - files.qmd
            - databases.qmd
            - services.qmd
        - section: "Enterprise"
          contents:
            - docker.qmd
            - snowflake.qmd
            - databricks.qmd
        - section: "Technology"
          contents:
            - quickstart.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

