project:
  type: website
  output-dir: docs
website:
  title: "Hal9"
  site-url: https://hal9.com/notebooks/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - getstarted.qmd
      - examples.qmd
      - href: https://hal9.com/notebooks/r
        text: R documentation
      - href: https://hal9.com/notebooks/python
        text: Python documentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



